version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: turns_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: turns_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # This line is crucial!

volumes:
  db_data:
